packages:
  - apps/docs
  - apps/web
  - packages/core
  - packages/utils
catalog:
  axios: ^1.0.0
  lodash: ^4.0.0
  react: ^18.0.0
  zod: ^3.0.0
catalogs:
  backend:
    cors: ^2.0.0
    dotenv: ^16.0.0
    express: ^4.0.0
